/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./../components/custom/app-provider.vue')['default']
    BetterScroll: typeof import('./../components/custom/better-scroll.vue')['default']
    Carousel: typeof import('./../components/custom/carousel.vue')['default']
    DarkModeContainer: typeof import('./../components/common/dark-mode-container.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ImagePreview: typeof import('./../components/custom/image-preview.vue')['default']
    LazyImage: typeof import('./../components/custom/lazy-image.vue')['default']
    MasonryLayout: typeof import('./../components/custom/masonry-layout.vue')['default']
    ModalDialog: typeof import('./../components/custom/modal-dialog.vue')['default']
    ParticleBg: typeof import('./../components/custom/particle-bg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTabs: typeof import('./../components/custom/scroll-tabs.vue')['default']
    Select: typeof import('./../components/custom/select.vue')['default']
    Steps: typeof import('./../components/custom/steps.vue')['default']
    SvgIcon: typeof import('./../components/custom/svg-icon.vue')['default']
    SystemLogo: typeof import('./../components/common/system-logo.vue')['default']
    VibecodingCarousel: typeof import('./../components/custom/vibecoding-carousel.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const AppProvider: typeof import('./../components/custom/app-provider.vue')['default']
  const BetterScroll: typeof import('./../components/custom/better-scroll.vue')['default']
  const Carousel: typeof import('./../components/custom/carousel.vue')['default']
  const DarkModeContainer: typeof import('./../components/common/dark-mode-container.vue')['default']
  const ElAvatar: typeof import('element-plus/es')['ElAvatar']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElImage: typeof import('element-plus/es')['ElImage']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElTabPane: typeof import('element-plus/es')['ElTabPane']
  const ElTabs: typeof import('element-plus/es')['ElTabs']
  const ImagePreview: typeof import('./../components/custom/image-preview.vue')['default']
  const LazyImage: typeof import('./../components/custom/lazy-image.vue')['default']
  const MasonryLayout: typeof import('./../components/custom/masonry-layout.vue')['default']
  const ModalDialog: typeof import('./../components/custom/modal-dialog.vue')['default']
  const ParticleBg: typeof import('./../components/custom/particle-bg.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const ScrollTabs: typeof import('./../components/custom/scroll-tabs.vue')['default']
  const Select: typeof import('./../components/custom/select.vue')['default']
  const Steps: typeof import('./../components/custom/steps.vue')['default']
  const SvgIcon: typeof import('./../components/custom/svg-icon.vue')['default']
  const SystemLogo: typeof import('./../components/common/system-logo.vue')['default']
  const VibecodingCarousel: typeof import('./../components/custom/vibecoding-carousel.vue')['default']
}