/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DarkModeContainer: typeof import('./../components/common/dark-mode-container.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    ParticleBg: typeof import('./../components/custom/particle-bg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/custom/svg-icon.vue')['default']
    SystemLogo: typeof import('./../components/common/system-logo.vue')['default']
    VibeCodingWaterfall: typeof import('./../components/custom/vibe-coding-waterfall.vue')['default']
  }
}

// For TSX support
declare global {
  const DarkModeContainer: typeof import('./../components/common/dark-mode-container.vue')['default']
  const NButton: typeof import('naive-ui')['NButton']
  const ParticleBg: typeof import('./../components/custom/particle-bg.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SvgIcon: typeof import('./../components/custom/svg-icon.vue')['default']
  const SystemLogo: typeof import('./../components/common/system-logo.vue')['default']
  const VibeCodingWaterfall: typeof import('./../components/custom/vibe-coding-waterfall.vue')['default']
}